name: Feature Request
description: Suggest a new feature or package manager
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like?
      placeholder: Describe the feature or package manager you'd like supported
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Why?
      placeholder: What problem does this solve for you?
