#!/bin/sh
set -eu

message_file=${1:-}
context=${2:-commit}

if [ -z "$message_file" ] || [ ! -f "$message_file" ]; then
	printf '%s\n' "commit policy: missing commit message file" >&2
	exit 1
fi

tmp_message=$(mktemp)
trap 'rm -f "$tmp_message"' EXIT HUP INT TERM

awk '
	/^# ------------------------ >8 ------------------------/ { exit }
	/^[[:space:]]*#/ { next }
	{ print }
' "$message_file" > "$tmp_message"

fail() {
	printf '%s\n' "commit policy: $1" >&2
	if [ "$context" = "push" ] && [ "${3:-}" ]; then
		printf '%s\n' "commit policy: rejected commit $3" >&2
	fi
	exit 1
}

subject=$(awk 'NF { print; exit }' "$tmp_message")

if [ -z "$subject" ]; then
	fail "write a non-empty commit subject"
fi

subject_len=$(printf '%s' "$subject" | awk '{ print length }')
if [ "$subject_len" -lt 10 ]; then
	fail "write a more specific commit subject"
fi

if [ "$subject_len" -gt 72 ]; then
	fail "keep the commit subject at 72 characters or fewer"
fi

case "$subject" in
	*.)
		fail "do not end the commit subject with a period"
		;;
esac

if grep -Eiq '^[[:space:]]*co[- ]?authored[- ]?by[[:space:]]*:' "$tmp_message"; then
	fail "Co-authored-by footers are not allowed"
fi

if grep -Eiq '(generated with|generated by|written by|created by).*(claude|chatgpt|codex|copilot|cursor|openai|anthropic|ai assistant)' "$tmp_message"; then
	fail "AI attribution footers are not allowed"
fi

if grep -Eiq '(claude code|chatgpt|github copilot|cursor ai|openai codex).*(generated|authored|co-authored|commit)' "$tmp_message"; then
	fail "AI attribution footers are not allowed"
fi

if grep -q -- '--' "$tmp_message"; then
	fail "double hyphen is not allowed in commit messages"
fi

unicode_dash_pattern=$(printf '\342\200\223|\342\200\224')
if grep -Eq "$unicode_dash_pattern" "$tmp_message"; then
	fail "Unicode dash characters are not allowed in commit messages"
fi

normalized_subject=$(
	printf '%s' "$subject" |
		tr '[:upper:]' '[:lower:]' |
		sed 's/[^a-z0-9][^a-z0-9]*/ /g; s/^ //; s/ $//'
)

case "$normalized_subject" in
	wip|work\ in\ progress|update|updates|change|changes|fix|fixes|cleanup|misc|misc\ changes|minor\ changes|minor\ fixes|bug\ fixes|address\ feedback|apply\ feedback|requested\ changes|final\ changes|various\ changes|various\ updates|make\ changes|apply\ changes|update\ files|update\ code|update\ repo|update\ project|fix\ issues|fix\ bugs|ai\ changes|automated\ changes)
		fail "generic AI-style commit subjects are not allowed"
		;;
esac

first_word=$(printf '%s\n' "$normalized_subject" | awk '{ print $1 }')
word_count=$(printf '%s\n' "$normalized_subject" | awk '{ print NF }')

case "$first_word" in
	add|change|cleanup|fix|improve|refactor|remove|update)
		if [ "$word_count" -lt 3 ]; then
			fail "commit subject needs enough context after '$first_word'"
		fi
		;;
esac

exit 0
