name        = "Catppuccin Mocha"
type        = "dark"
author      = "catppuccin"
description = "Soothing pastel theme for the high-spirited"

background  = "#1e1e2e"
foreground  = "#cdd6f4"
accent      = "#cba6f7"
cursor      = "#f5e0dc"
highlight   = "#b4befe"
border      = "#585b70"
selection   = "#313244"
surface     = "#313244"
subtext     = "#6c7086"
text        = "#cdd6f4"
blue        = "#89b4fa"
purple      = "#cba6f7"
green       = "#a6e3a1"
red         = "#f38ba8"
yellow      = "#f9e2af"
cyan        = "#89dceb"
orange      = "#fab387"
white       = "#bac2de"
