name        = "Dracula"
type        = "dark"
author      = "Zeno Rocha"
description = "A dark theme for all your text editors and development tools"

background  = "#282a36"
foreground  = "#f8f8f2"
accent      = "#bd93f9"
cursor      = "#ff79c6"
highlight   = "#6272a4"
border      = "#44475a"
selection   = "#44475a"
surface     = "#44475a"
subtext     = "#6272a4"
text        = "#f8f8f2"
blue        = "#6272a4"
purple      = "#bd93f9"
green       = "#50fa7b"
red         = "#ff5555"
yellow      = "#f1fa8c"
cyan        = "#8be9fd"
orange      = "#ffb86c"
white       = "#f8f8f2"
